apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - image: busybox
    name: pod
    command: ["sh","-c","sleep 3600"]
    volumeMounts:
    - name: config
      mountPath: /etc/config.conf
      readOnly: true
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: config
    hostPath:
      path: /tmp/config.conf
      type: FileOrCreate
status: {}