#https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true # will extend pvc later
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-storage-pv
  labels:
    type: local
spec:
  storageClassName: manual # storage class name
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/data"
  persistentVolumeReclaimPolicy: Recycle  # auto recycle 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-storage-pvc
spec:
  storageClassName: manual # storage class name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # init size, could be resize later
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: host-storage-pvc  # pvc name
  containers:
    - name: busybox
      image: busybox
      command: ["sh","-c","while true; do echo success > /output/output.log; sleep 5; done"]
      volumeMounts:
        - mountPath: "/output"
          name: task-pv-storage
